name: nostrrdr
description: "Nostr reader."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0
dependencies:
  flutter:
    sdk: flutter
  amberflutter: ^0.0.4
  file_picker: ^10.3.7
  flutter_secure_storage: ^10.0.0
  path: ^1.8.3
  path_provider: ^2.1.0
  pdfrx: ^2.2.18
  uuid: ^4.0.0
  toastification: ^3.0.3
  flutter_screenutil: ^5.9.3
  get_it: ^9.2.0
  injectable: ^2.7.1+2
  auto_route: ^11.0.0
  flutter_bloc: ^9.1.1
  bloc_test: ^10.0.0
  hydrated_bloc: ^10.1.1
  google_fonts: ^6.3.3
  flutter_rust_bridge: ^2.11.1
  marmot_flutter:
    git:
      url: git@github.com:codeswot/marmot_flutter.git
  dartz: ^0.10.1
  logging: ^1.3.0
  equatable: ^2.0.7
  formz: ^0.8.0
  form_builder_validators: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  flutter_lints: ^6.0.0
  mocktail: ^1.0.0
  injectable_generator: ^2.7.0
  auto_route_generator: ^10.4.0

flutter:
  uses-material-design: true
